<?php
// $Id: environment_indicator.install,v 1.1.2.1 2009/11/29 20:35:11 mrfelton Exp $

/**
 * @file
 * Environment Indicator installation file.
 *
 * @author Tom Kirkpatrick (mrfelton), www.kirkdesigns.co.uk
 */

/**
 * Implementation of hook_install().
 */
function environment_indicator_uninstall($path, $arg) {
  db_query("DELETE FROM {variable} WHERE name LIKE 'environment_indicator_%'");
}

