<?php

define('SERVICECONNECT_HYVES_PATH_LOGIN', 'login-via-hyves');
define('SERVICECONNECT_HYVES_PATH_LINK', 'link-hyves-profile');
define('SERVICECONNECT_HYVES_PATH_DECLINE', 'login-via-hyves/decline-terms');
define('SERVICECONNECT_HYVES_PATH_ADMIN', 'admin/settings/serviceconnect/hyves');
define('SERVICECONNECT_HYVES_PATH_ADMIN_SETTINGS', 'admin/settings/serviceconnect/hyves/settings');
define('SERVICECONNECT_HYVES_PATH_ADMIN_TEST', 'admin/settings/serviceconnect/hyves/test');

define('SERVICECONNECT_HYVES_PERM_LOGIN', 'login via hyves');
define('SERVICECONNECT_HYVES_PERM_LINK', 'link hyves profile');

define('SERVICECONNECT_HYVES_VAR_CONSUMER_KEY', 'serviceconnect_hyves_consumer_key');
define('SERVICECONNECT_HYVES_VAR_CONSUMER_SECRET', 'serviceconnect_hyves_consumer_secret');
define('SERVICECONNECT_HYVES_VAR_CONSUMER_SECRET', 'serviceconnect_hyves_consumer_secret');

// OAuth specifies 3 different URL's for the authorisation process, which may be different
// see http://oauth.net/core/1.0a/#request_urls
define('SERVICECONNECT_HYVES_VAR_REQUEST_TOKEN_URL', 'serviceconnect_hyves_request_token_url');
define('SERVICECONNECT_HYVES_VAR_USER_AUTHORIZATION_URL', 'serviceconnect_hyves_user_authorization_url');
define('SERVICECONNECT_HYVES_VAR_ACCESS_TOKEN_URL', 'serviceconnect_hyves_access_token_url');
define('SERVICECONNECT_HYVES_VAR_API_URL', 'serviceconnect_hyves_api_url');
define('SERVICECONNECT_HYVES_VAR_REQUEST_TOKEN_URL_DEFAULT', 'http://data.hyves-api.nl/');
define('SERVICECONNECT_HYVES_VAR_USER_AUTHORIZATION_URL_DEFAULT', 'http://www.hyves.nl/api/authorize/');
define('SERVICECONNECT_HYVES_VAR_ACCESS_TOKEN_URL_DEFAULT', 'http://data.hyves-api.nl/');
define('SERVICECONNECT_HYVES_VAR_API_URL_DEFAULT', 'http://data.hyves-api.nl/');

define('SERVICECONNECT_HYVES_VAR_EXPIRATION_TYPE', 'serviceconnect_hyves_expiration_type');
define('SERVICECONNECT_HYVES_VAR_EXPIRATION_TYPE_DEFAULT', 'default');

define('SERVICECONNECT_HYVES_VAR_TERMS', 'serviceconnect_hyves_terms');

define('SERVICECONNECT_HYVES_VAR_PROFILEPICTURE_SIZE', 'serviceconnect_hyves_profilepicture_size');
define('SERVICECONNECT_HYVES_VAR_PROFILEPICTURE_SIZE_DEFAULT', 'icon_large');
define('SERVICECONNECT_HYVES_VAR_PROFILEPICTURE_PROFILE_FIELD', 'serviceconnect_hyves_profilepicture_profile_field');
define('SERVICECONNECT_HYVES_VAR_LINK_PROFILE_FIELD', 'serviceconnect_hyves_link_profile_field');
define('SERVICECONNECT_HYVES_VAR_FIRSTNAME_PROFILE_FIELD', 'serviceconnect_hyves_firstname_profile_field');
define('SERVICECONNECT_HYVES_VAR_LASTNAME_PROFILE_FIELD', 'serviceconnect_hyves_lastname_profile_field');
define('SERVICECONNECT_HYVES_VAR_GENDER_PROFILE_FIELD', 'serviceconnect_hyves_gender_profile_field');
define('SERVICECONNECT_HYVES_VAR_GENDER_PROFILE_FIELD_MALE', 'serviceconnect_hyves_gender_profile_field_male');
define('SERVICECONNECT_HYVES_VAR_GENDER_PROFILE_FIELD_FEMALE', 'serviceconnect_hyves_gender_profile_field_female');
define('SERVICECONNECT_HYVES_VAR_BIRTHDAY_PROFILE_FIELD', 'serviceconnect_hyves_birthday_profile_field');
define('SERVICECONNECT_HYVES_VAR_CITYNAME_PROFILE_FIELD', 'serviceconnect_hyves_cityname_profile_field');

define('SERVICECONNECT_HYVES_VAR_FRIENDS_RELATIONSHIP_TYPE', 'serviceconnect_hyves_friends_relationship_type');

/**
 * Used as servicename for serviceconnect
 *
 * @see _serviceconnect_hyves_page_oauth_callback()
 * @see serviceconnect_login_with_new_user()
 * @see serviceconnect_link_service()
 */
define('SERVICECONNECT_HYVES_SERVICE_NAME', 'hyves');

/**
 * MediaId for the default "Bassie" picture which shows on all newly created profiles
 */
define('SERVICECONNECT_HYVES_DEFAULT_PROFILEPICTURE_MEDIAID', 'fafcdf5be5da17fd');

/**
 * Implementation of hook_perm().
 */
function serviceconnect_hyves_perm() {
  return array(
    SERVICECONNECT_HYVES_PERM_LOGIN,
    SERVICECONNECT_HYVES_PERM_LINK,
  );
}

/**
 * Implementation of hook_menu().
 */
function serviceconnect_hyves_menu() {
  $menu = array();
  
  $menu[SERVICECONNECT_HYVES_PATH_LOGIN] = array(
    'page callback' => 'serviceconnect_hyves_page_login',
    'access arguments' => array(SERVICECONNECT_HYVES_PERM_LOGIN),
    'type' => MENU_CALLBACK,
  );
  
  $menu[SERVICECONNECT_HYVES_PATH_LINK] = array(
    'page callback' => 'serviceconnect_hyves_page_login',
    'page arguments' => array(TRUE),
    'access arguments' => array(SERVICECONNECT_HYVES_PERM_LINK),
    'type' => MENU_CALLBACK,
  );
  
  $menu[SERVICECONNECT_HYVES_PATH_DECLINE] = array(
    'page callback' => 'serviceconnect_hyves_page_decline',
    'access arguments' => array(SERVICECONNECT_HYVES_PERM_LOGIN),
    'type' => MENU_CALLBACK
  );
  
  $menu[SERVICECONNECT_HYVES_PATH_ADMIN] = array(
    'title' => 'Hyves',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('serviceconnect_hyves_settings_form'),
    'access arguments' => array(SERVICECONNECT_PERM_ADMINISTER),
    'type' => MENU_LOCAL_TASK,
    'file' => 'serviceconnect_hyves.admin.inc',
  );
  
  $menu[SERVICECONNECT_HYVES_PATH_ADMIN_SETTINGS] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('serviceconnect_hyves_settings_form'),
    'access arguments' => array(SERVICECONNECT_PERM_ADMINISTER),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'serviceconnect_hyves.admin.inc',
  );
  
  $menu[SERVICECONNECT_HYVES_PATH_ADMIN_TEST] = array(
    'title' => 'Test connection',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('serviceconnect_hyves_admin_test_page'),
    'access arguments' => array(SERVICECONNECT_PERM_ADMINISTER),
    'type' => MENU_LOCAL_TASK,
    'file' => 'serviceconnect_hyves.admin.inc',
  );
  
  return $menu;
}

/**
 * Menu callback for loginpage.
 */
function serviceconnect_hyves_page_login($link_hyves_to_user = FALSE){
  if (!empty($_GET['sid']) && !empty($_GET['h']) && _serviceconnect_hyves_secret_hash($_GET['sid']) == $_GET['h']){
    $sql = 'SELECT token FROM {serviceconnect_hyves_auth_session} WHERE sid = %d';
    $res = db_query($sql, $_GET['sid']);
    return _serviceconnect_hyves_page_oauth_callback(db_result($res), 2);
  } elseif (!empty($_GET['oauth_token'])) {
    return _serviceconnect_hyves_page_oauth_callback($_GET['oauth_token']);
  } else {
    return _serviceconnect_hyves_page_new($link_hyves_to_user);
  }
}

/**
 * Process OAuth callback.
 */
function _serviceconnect_hyves_page_oauth_callback($token, $phase = 1, $username = NULL, $email = NULL) {
  global $user;
  
  try {
    $sql = 'SELECT s.sid, s.uid, s.link, s.token, s.token_secret, s.created, s.timestamp_difference, s.service_uid, s.expires
    FROM {serviceconnect_hyves_auth_session} s
    WHERE s.token = \'%s\'';
    $res = db_query($sql, $token);
    if (!$session = db_fetch_object($res)) {
      throw new Exception('Session id not found');
    }
    $token_secret = $session->token_secret;
    $service_user_id = $session->service_uid;
    $expire_date = $session->expires;
    
    if ($session->uid != (int) $user->uid) {
      // This is to prevent session fixation attack using to following flow:
      // 1) Alice clicks on login with Hyves, does not nothing on the Hyves page but
      //    redirects Bob to the URI
      // 2) Bob goes to that URI and grants permission with his Hyves account
      // 3) Alice requests access token and is now authorized with Bob's Hyves
      // This does not fix the problem if both Alice and Bob are not logged in on Drupal,
      // see http://oauth.net/advisories/2009-1/ for details
      throw new Exception('Authorisation session was initiated by another user');
    }
    
    try {
      if ($phase == 1) {
        // Request access token (note that $session->tokenis the _authorisation_ token)
        module_load_include('inc', 'serviceconnect_hyves', 'calls/auth.accesstoken');
        $response = serviceconnect_hyves_call_auth_accesstoken($session->token, $session->token_secret);
        extract($response); // Introduces $token, $token_secret, $service_user_id and $expire_date
        $sql = 'UPDATE {serviceconnect_hyves_auth_session}
        SET token = \'%s\', token_secret = \'%s\', service_uid = \'%s\'
        WHERE sid = %d';
        db_query($sql, $token, $token_secret, $service_user_id, $session->sid);
        // Delete old sessions with the same token (this happens when the user still has a valid token)
        $sql = 'DELETE FROM {serviceconnect_hyves_auth_session} WHERE token = \'%s\' AND sid != %d';
        db_query($sql, $token, $session->sid);
      }
      
      // Request user profile information
      module_load_include('inc', 'serviceconnect_hyves', 'calls/users.get');
      $profile = serviceconnect_hyves_call_users_get($service_user_id, $token, $token_secret);
    } catch (Exception $e){
      drupal_set_message(t('Login with Hyves failed. You probably rejected permission.'), 'error');
      watchdog('ServiceConnect', $e->getMessage().' (probably rejected permission)', array(), WATCHDOG_ALERT);
      drupal_goto('');
      return '';
    }
    
    $first_use = FALSE;
    $scprofile = serviceconnect_get_uid_by_service_uid(SERVICECONNECT_HYVES_SERVICE_NAME, $service_user_id);
    
    // Generate username / email form (only when not linking profile to current user).
    if (!$session->link || !user_is_logged_in()) {
      // Not a registered user yet (or unlinked)
      if (!$scprofile && $phase == 1) {
        $h = _serviceconnect_hyves_secret_hash($session->sid);
        drupal_goto($_GET['q'], "sid={$session->sid}&h=$h");
        return '';
      }
      elseif (!$scprofile && $phase == 2) {
        return drupal_get_form(
          'serviceconnect_register_form',
          'serviceconnect_hyves',
          $token,
          $profile['displayname'],
          variable_get(SERVICECONNECT_HYVES_VAR_TERMS, ''),
          SERVICECONNECT_HYVES_SERVICE_NAME
        );
      }
    }

    // Log the user in.
    if (user_is_logged_in()) {
      if ($session->link) {
        if ($scprofile->uid) {
          if ($scprofile->uid != $user->uid) {
            // The Hyves account already has another Drupal account linked (called $service_uid),
            // The user already has an account which he uses, the flow to get here is:
            // 1) Login via Hyves (without migrating) -> generates a new account
            // 2) Try to link old account with their Hyves account
            drupal_set_message(t('Unable to link Hyves account to your user, this Hyves account is already in use for another account'), 'error');
          } else {
            // User is already migrated, stay logged in with $user->uid,
            // however, call this function to update statistics
            serviceconnect_login_with_existing_user($scprofile->scpid, $scprofile->uid, $expire_date);
            drupal_set_message(t('Succesfully logged in with Hyves'));
          }
        } else {
          // This is the usual migration, no Hyves account is linked to the Drupal account yet
          $scpid = serviceconnect_link_service(SERVICECONNECT_HYVES_SERVICE_NAME, $service_user_id,
            $profile['service_profile_url'], $profile['displayname'], $expire_date);
          drupal_set_message(t('Your Hyves profile is now linked to your account'));
          $first_use = TRUE;
        }
      } else {
        if ($scprofile->uid) {
          serviceconnect_login_with_existing_user($scprofile->scpid, $scprofile->uid, $expire_date);
          drupal_set_message(t('Succesfully logged in with Hyves'));
        } else {
          // We are already logged in, but want to login with another account via Hyves
          $uid = serviceconnect_login_with_new_user(SERVICECONNECT_HYVES_SERVICE_NAME, $service_user_id, $username, $email);
          $scpid = serviceconnect_link_service(SERVICECONNECT_HYVES_SERVICE_NAME, $service_user_id,
            $profile['service_profile_url'], $profile['displayname'], $expire_date);
          drupal_set_message(t('Succesfully logged in with Hyves'));
          $first_use = TRUE;
        }
      }
    } else {
      if ($scprofile->uid) {
        serviceconnect_login_with_existing_user($scprofile->scpid, $scprofile->uid, $expire_date);
        drupal_set_message(t('Succesfully logged in with Hyves'));
      } else {
        $uid = serviceconnect_login_with_new_user(SERVICECONNECT_HYVES_SERVICE_NAME, $service_user_id, $username, $email);
        $scpid = serviceconnect_link_service(SERVICECONNECT_HYVES_SERVICE_NAME, $service_user_id,
          $profile['service_profile_url'], $profile['displayname'], $expire_date);
        drupal_set_message(t('Succesfully logged in with Hyves'));
        $first_use = TRUE;
      }
    }
    
    if (empty($scpid)) {
      $scpid = $scprofile->scpid;
    }
    $sql = 'SELECT suh.profilepicture_mediaid, suh.friendscount
    FROM {serviceconnect_user_hyves} suh
    WHERE suh.scpid = %d';
    $res = db_query($sql, $scpid);
    if ($rec = db_fetch_array($res)) {
      $old_profilepicture_mediaid = $rec['profilepicture_mediaid'];
      $old_friendscount = $rec['friendscount'];
      $sql = 'UPDATE {serviceconnect_user_hyves} SET
      token = \'%s\',
      token_secret = \'%s\',
      profilepicture_mediaid = \'%s\',
      friendscount = %d,
      accepted_terms = CASE accepted_terms WHEN 1 THEN 1 ELSE %d END
      WHERE scpid = %d';
      db_query($sql, $token, $token_secret, $profile['profilepicture_mediaid'], $profile['friendscount'], $phase == 1 ? 0 : 1, $scpid);
    } else {
      $old_profilepicture_mediaid = '';
      $old_friendscount = 0;
      
      $suh = new stdClass();
      $suh->scpid = $scpid;
      $suh->token = $token;
      $suh->token_secret = $token_secret;
      $suh->firstname = $profile['firstname'];
      $suh->lastname = $profile['lastname'];
      $suh->gender = $profile['gender'];
      $suh->birthday = $profile['birthday'];
      $suh->profilepicture_mediaid = $profile['profilepicture_mediaid'];
      $suh->friendscount = $profile['friendscount'];
      $suh->accepted_terms = $phase == 1 ? 0 : 1;
      drupal_write_record('serviceconnect_user_hyves', $suh);
    }
  } catch (Exception $e){
    drupal_set_message(t('Unable to login with Hyves'), 'error');
    watchdog('ServiceConnect', $e->getMessage(), array(), WATCHDOG_ALERT);
    drupal_goto('');
    return '';
  }
  
  // We are now logged in, import profile information from Hyves
  try {
    // Import information into profile fields
    $profile_fields = array(
      SERVICECONNECT_HYVES_VAR_FIRSTNAME_PROFILE_FIELD => $profile['firstname'],
      SERVICECONNECT_HYVES_VAR_LASTNAME_PROFILE_FIELD => $profile['lastname'],
      SERVICECONNECT_HYVES_VAR_GENDER_PROFILE_FIELD => $profile['gender'],
      SERVICECONNECT_HYVES_VAR_BIRTHDAY_PROFILE_FIELD => $profile['birthday'],
      SERVICECONNECT_HYVES_VAR_CITYNAME_PROFILE_FIELD => $profile['cityname'],
      SERVICECONNECT_HYVES_VAR_LINK_PROFILE_FIELD => $profile['service_profile_url'],
    );
    
    switch ($profile['gender']) {
      case 'male':
        $gender = variable_get(SERVICECONNECT_HYVES_VAR_GENDER_PROFILE_FIELD_MALE, 'male');
        break;
      case 'female':
        $gender = variable_get(SERVICECONNECT_HYVES_VAR_GENDER_PROFILE_FIELD_MALE, 'female');
        break;
      default:
        $gender = '';
        break;
    }
    $profile_fields[SERVICECONNECT_HYVES_VAR_GENDER_PROFILE_FIELD] = $gender;
    
    $birthday = explode('-', $profile['birthday']);
    $birthday = array(
      'day' => (int) $birthday[2],
      'month' => (int) $birthday[1],
      'year' => (int) $birthday[0]
    );
    $birthday = serialize($birthday);
    $profile_fields[SERVICECONNECT_HYVES_VAR_BIRTHDAY_PROFILE_FIELD] = $birthday;

    // Download profilepicture
    if ($old_profilepicture_mediaid != $profile['profilepicture_mediaid']) {
      if (isset($profile['profilepicture_src']) && $profile['profilepicture_mediaid'] != SERVICECONNECT_HYVES_DEFAULT_PROFILEPICTURE_MEDIAID) {
        $profile_fields[SERVICECONNECT_HYVES_VAR_PROFILEPICTURE_PROFILE_FIELD] = $profile['profilepicture_src'];
      }
    }

    $fields = array();
    foreach ($profile_fields as $var => $value) {
      if ($field = variable_get($var, '')) {
        $fields[$field] = $value;
      }
    }
    serviceconnect_save_profile($fields);
    
    // Invoke hook_serviceconnect_hyves_update_profile
    module_invoke_all(
      'serviceconnect_hyves_update_profile',
      $profile['firstname'],
      $profile['lastname'],
      $gender,
      $birthday,
      $profile['cityname']
    );
    
    // Import new friends (if any and enabled)
    if ($old_friendscount != $profile['friendscount'] && $rtid = variable_get(SERVICECONNECT_HYVES_VAR_FRIENDS_RELATIONSHIP_TYPE, '')) {
      module_load_include('inc', 'serviceconnect_hyves', 'calls/friends.get');
      $friends = serviceconnect_hyves_call_friends_get($token, $token_secret);
      $imported = serviceconnect_import_user_relationships(SERVICECONNECT_HYVES_SERVICE_NAME, $friends, $rtid);
    }
    
    $redirect = '';
    if ($first_use && !$session->link){
      $redirect = serviceconnect_first_use(t(SERVICECONNECT_HYVES_SERVICE_NAME));
    }
    $redirect or $redirect = 'user';
    drupal_goto($redirect);
    return '';
  } catch (Exception $e){
    drupal_set_message(t('Unable to import profile information from Hyves'), 'error');
    watchdog('ServiceConnect', $e->getMessage(), array(), WATCHDOG_ALERT);
    drupal_goto('');
    return '';
  }
}

/**
 * Callback for first time login via Hyves.
 */
function _serviceconnect_hyves_page_new($link_hyves_to_user = FALSE){
  global $user;
  
  try {
    module_load_include('inc', 'serviceconnect_hyves', 'calls/auth.requesttoken');
    $values = serviceconnect_hyves_call_auth_requesttoken();
    
    // Write session to database
    $session = new stdClass();
    $session->uid = (int) $user->uid;
    $session->link = $link_hyves_to_user ? 1 : 0;
    $session->token = $values['oauth_token'];
    $session->token_secret = $values['oauth_token_secret'];
    $session->timestamp_difference = $values['timestamp_difference'];
    $session->created = time();
    if (!drupal_write_record('serviceconnect_hyves_auth_session', $session)) {
      throw new Exception('Error writing session information while trying to login via Hyves');
    }
    
    // Redirect to the Hyves authorisation page
    $callback = 'http://'.$_SERVER['HTTP_HOST'].'/'.SERVICECONNECT_HYVES_PATH_LOGIN.'?sid='.$session->sid;
    $query = 'oauth_token='.urlencode($session->token).'&oauth_callback='.urlencode($callback);
    $url = variable_get(SERVICECONNECT_HYVES_VAR_USER_AUTHORIZATION_URL, SERVICECONNECT_HYVES_VAR_USER_AUTHORIZATION_URL_DEFAULT);
    drupal_goto($url, $query);
  } catch (Exception $e){
    drupal_set_message(t('Unable to login with Hyves'), 'error');
    watchdog('ServiceConnect', $e->getMessage(), array(), WATCHDOG_ALERT);
    drupal_goto('');
    return '';
  }
}

/**
 * Fetch values from XML response.
 * 
 * @param DOMDocument $document
 * @return array
 * @see _serviceconnect_hyves_request()
 */
function _serviceconnect_hyves_values_from_xml($document){
  $root = $document->documentElement;
  if (!$root->hasChildNodes()) {
    drupal_set_message(t('Invalid response from Hyves'), 'error');
    return;
  }
  
  $values = array();
  $node = $root->firstChild;
  do {
    if ($node->nodeName == 'info') {
      if (!$node->hasChildNodes()) {
        continue;
      }
      $info_node = $node->firstChild;
      do {
        $values[$info_node->nodeName] = $info_node->textContent;
      } while ($info_node = $info_node->nextSibling);
    } else {
      $values[$node->nodeName] = $node->textContent;
    }
  } while ($node = $node->nextSibling);
  
  return $values;
}

/**
 * Send a request to the Hyves API.
 *
 * @param array $params
 * @param string $url
 * @param string $token
 * @param string $token_secret
 * @return array
 */
function _serviceconnect_hyves_request($params, $url, $token = '', $token_secret = '') {
  module_load_include('php', 'serviceconnect', 'oauth.lib');
  
  // We use this for the test connection page
  global $_serviceconnect_hyves_last_response;
  $_serviceconnect_hyves_last_response = NULL;
  
  $key = variable_get(SERVICECONNECT_HYVES_VAR_CONSUMER_KEY, '');
  $secret = variable_get(SERVICECONNECT_HYVES_VAR_CONSUMER_SECRET, '');
  
  try {
    $consumer = new OAuthConsumer($key, $secret);
    $token = new OAuthToken($token, $token_secret);
    
    $params['oauth_consumer_key'] = $key;
    $params['oauth_signature_method'] = 'HMAC-SHA1';
    $params['oauth_version'] = '1.0';
    $request = OAuthRequest::from_consumer_and_token($consumer, $token, 'GET', $url, $params);
    
    $signature_method = new OAuthSignatureMethod_HMAC_SHA1();
    $request->sign_request($signature_method, $consumer, $token);
    
    $query = $request->to_postdata();
    
    $response = drupal_http_request($url.'?'.$query);
    $_serviceconnect_hyves_last_response = $response;
    if ($response->code != 200){
      return FALSE;
    }
    
    $dom = DOMDocument::loadXML($response->data);
    
    //$dom->formatOutput = TRUE;
    //$xml = $dom->saveXML();
    //dsm($xml);
    
    return $dom;
  } catch (OAuthException $e){
    // Display the detailed error only for users with administer serviceconnect permission
    if (user_access(SERVICECONNECT_PERM_ADMINISTER)) {
      drupal_set_message($e->getMessage(), 'error');
    }
    return FALSE;
  }
}

/**
 * Get token for currently logged in user.
 *
 * @return array Associative array with keys 'token' and 'token_secret'
 */
function serviceconnect_hyves_get_active_token() {
  global $user;
  if (!$scpid = serviceconnect_get_scpid_by_service(SERVICECONNECT_HYVES_SERVICE_NAME)) {
    return FALSE;
  }
  $sql = 'SELECT suh.token, suh.token_secret
  FROM {serviceconnect_user_hyves} suh
  WHERE suh.scpid = %d';
  $res = db_query($sql, $scpid);
  return db_fetch_array($res);
}

/**
 * Implements hook_cron().
 *
 * Clear old sessions from database.
 */
function serviceconnect_hyves_cron() {
  $sql = 'DELETE FROM {serviceconnect_hyves_auth_session} WHERE created < %d';
  db_query($sql, time() - (3600 * 6));
}

/**
 * Get a secret hash.
 *
 * We cannot use drupal_get_token() because the token may not invalidate on another session.
 *
 * @param string $data
 * @return string
 */
function _serviceconnect_hyves_secret_hash($data) {
  $secret = drupal_get_private_key();
  return substr(md5($data.$secret), 0, 16);
}

/**
 * Callback for decline link on terms page.
 */
function serviceconnect_hyves_page_decline() {
  serviceconnect_increment_counter('hyves terms declined');
  if (isset($_GET['scpid'])) {
    $scpid = $_GET['scpid'];
    if ($_GET['h'] == _serviceconnect_hyves_secret_hash($scpid)) {
      serviceconnect_clear_user_data($scpid);
      $sql = 'DELETE FROM {serviceconnect_user_hyves} WHERE scpid = %d';
      db_query($sql, $scpid);
    }
  }
  drupal_goto('user');
}

/**
 * Register callback for serviceconnect module.
 *
 * @see serviceconnect_register_form_submit()
 */
function serviceconnect_hyves_register($token, $username, $email) {
  _serviceconnect_hyves_page_oauth_callback($token, 3, $username, $email);
}