<?php
/**
 * @file denaske.module
 * TODO: Enter file description here.
 */


function denask_perm(){
  
  return array('config denaske');
  
}

/**
 * Implementation of hook_menu().
 */
function denaske_menu() { 
  // This is the minimum information you can provide for a menu item.
  $items['admin/denaske'] = array(
    'title' => 'Denaske config',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('denaske_settings_form'),
    'file' => 'admin_settings_form.inc',
    'access arguments' => array('config denaske'),
  );
  
  
  
  /*
  // more complex menu item
  $items['TODO: Enter path'] = array(
    'title' => 'TODO: Enter menu item title',
    'description' => 'TODO: Enter description',
    'page callback' => 'TODO: Enter callback function',
    'page arguments' => '', // An array of arguments to pass to the page callback function. Integer values pass the corresponding URL component.
    'access callback' => '', // defaults to user_access()
    'access arguments' => array('TODO: Enter user permissions'),
    'weight' => 0,
    'type' => MENU_NORMAL_ITEM, // One of MENU_NORMAL_ITEM / MENU_CALLBACK / MENU_SUGGESTED_ITEM / MENU_LOCAL_TASK / MENU_DEFAULT_LOCAL_TASK
    'menu_name' => '', // Menu to place this item in.
    'title callback' => '', // Function to generate the title, defaults to t(). 
    'title arguments' => '', // Arguments to send to t() or your custom callback. 
  );*/
  // OPTIONAL: Fill in additional static menu items

  return $items;
}


/**
 * Implementation of hook_form_alter().
 */
function denaske_form_alter(&$form, &$form_state, $form_id) {

}


